import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';

export async function generateAnalysisPDF(coupleId, analysis) {
    return new Promise((resolve, reject) => {
        try {
            const reportsDir = path.join(process.cwd(), 'reports');
            if (!fs.existsSync(reportsDir)) {
                fs.mkdirSync(reportsDir);
            }

            const fileName = `Analysis_Report_${coupleId}_${Date.now()}.pdf`;
            const filePath = path.join(reportsDir, fileName);
            const doc = new PDFDocument({ margin: 50 });

            const stream = fs.createWriteStream(filePath);
            doc.pipe(stream);

            // Header - Bandhan Marriage Analysis
            doc.fillColor('#2c3e50')
                .fontSize(25)
                .text('Bandhan Marriage Analysis Report', { align: 'center' });

            doc.moveDown();
            doc.fontSize(12).fillColor('#7f8c8d').text(`Couple ID: ${coupleId}`, { align: 'center' });
            doc.text(`Generated on: ${new Date().toLocaleString()}`, { align: 'center' });

            doc.moveDown(2);
            doc.rect(50, doc.y, 500, 2).fill('#3498db');
            doc.moveDown();

            // Decision Box
            const decisionColor = analysis.decision === 'Green' ? '#27ae60' :
                analysis.decision === 'Amber' ? '#f39c12' : '#c0392b';

            doc.fontSize(16).fillColor('#2c3e50').text('Overall Decision:', { continued: true });
            doc.fillColor(decisionColor).text(` ${analysis.decision}`, { stroke: true });

            doc.moveDown();
            doc.fillColor('#2c3e50').fontSize(12).text(`Confidence Score: ${(analysis.confidence * 100).toFixed(0)}%`);

            doc.moveDown(1.5);

            // Expert Consensus
            doc.fontSize(14).fillColor('#2980b9').text('Expert Panel Consensus');
            doc.moveDown(0.5);
            doc.fontSize(11).fillColor('#34495e').text(analysis.expert_consensus, {
                align: 'justify',
                lineGap: 2
            });

            doc.moveDown(1.5);

            // Risks
            doc.fontSize(14).fillColor('#e74c3c').text('Key Risks Identified');
            doc.moveDown(0.5);
            analysis.risks.forEach(risk => {
                doc.fontSize(11).fillColor('#34495e').text(`• ${risk}`, { indent: 20 });
            });

            doc.moveDown(1.5);

            // Advice
            doc.fontSize(14).fillColor('#27ae60').text('Strategic Advice');
            doc.moveDown(0.5);
            analysis.advice.forEach(item => {
                doc.fontSize(11).fillColor('#34495e').text(`• ${item}`, { indent: 20 });
            });

            // Footer
            const bottom = doc.page.height - 50;
            doc.fontSize(10).fillColor('#bdc3c7').text('This report is generated by Bandhan AI MCP System.', 50, bottom, { align: 'center' });

            doc.end();

            stream.on('finish', () => {
                resolve({
                    fileName,
                    filePath,
                    relativeUrl: `/reports/${fileName}`
                });
            });
        } catch (error) {
            reject(error);
        }
    });
}
